# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后台开发', max_length=20, verbose_name='课程类别'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初级'), ('gj', '高级'), ('zj', '中级')], default='cj', max_length=5, verbose_name='课程难度'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='服务操作系统', max_length=40, verbose_name='课程标签'),
        ),
    ]
