# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='机构名字')),
                ('desc', models.CharField(max_length=80, verbose_name='机构描述')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏此书')),
                ('image', models.ImageField(upload_to='courses/org/%Y/%m', verbose_name='机构图像')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CityDict', verbose_name='机构城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='讲师名字')),
                ('work_year', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_company', models.CharField(max_length=200, verbose_name='工作单位')),
                ('work_position', models.CharField(max_length=100, verbose_name='工作职位')),
                ('point', models.CharField(max_length=400, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击次数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏此书')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('courseorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师详情',
                'verbose_name_plural': '讲师详情',
            },
        ),
    ]
